name: Lint Code

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

jobs:
  lint:
    runs-on: ubuntu-latest # or your preferred runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI

      - name: Run Linters
        run: npm run lint # Execute the lint script defined in package.json